# Generated by Django 6.0.5 on 2026-06-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contract_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='contract_signed',
            field=models.BooleanField(default=False),
        ),
    ]
